#!/bin/bash
# archivedir--Creates a compressed archive of the specified directory.

maxarchivedir=10           # Size, in blocks, of 'big' directory
compress=gzip              # Change to your favorite compress app.
progname=$(basename $0)    # Nicer output format for error messages
#basename is the program name archivdir $0 means

if [ $# -eq 0 ] ; then      # No args? That's a problem. | $# = Number of paramaters used, -eq = equals.  Thus, If no paramaters used go to next line
  echo "Usage: $progname directory" >&2 ;exit 1 #Print Usage: archivedir  directory and exit program
fi # End if Statement

if [ ! -d $1 ] ; then
  echo "${progname}: can't find directory $1 to archive." >&2; exit 1
fi # End if Statement

if [ "$(basename $1)" != "$1" -o "$1" = "." ] ; then 
  echo "${progname}: you must specify a subdirectory" >&2
  exit 1
fi # End if Statement

if [ ! -w . ] ; then
  echo "${progname}: cannot write archive file to current directory." >&2
  exit 1
fi # End if Statement

# Is the resultant archive going to be dangerously big? Let's check...

dirsize="$(du -s $1 | awk '{print $1}')"

if [ $dirsize -gt $maxarchivedir ] ; then
  echo -n "Warning: directory $1 is $dirsize blocks. Proceed? [n] " 
  read answer
  answer="$(echo $answer | tr '[:upper:]' '[:lower:]' | cut -c1)"
  if [ "$answer" != "y" ] ; then
    echo "${progname}: archive of directory $1 canceled." >&2
    exit 0
  fi # End inner if Statement
fi # End outer if Statement

archivename="$1.tgz"

if tar cf - $1 | $compress > $archivename ; then
  echo "Directory $1 archived as $archivename"
else
  echo "Warning: tar encountered errors archiving $1" 
fi # End if Statement

exit 0
